version: '3'
services:
  app:
    build: .
    entrypoint: ./docker_entry.sh
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/diyrss_app
    environment:
      - DATABASE_HOST=db
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=diyrss
      - POSTGRES_DB=diyrss_production
    ports:
      - 5432:5432
    volumes:
      - .:/db

  redis_db:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - .:/redis_db

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis_db

  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - 'app'
    ports:
      - 80:80
