default: &default
  adapter:  postgresql
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  timeout: 5000

development:
  <<: *default
  database: diyrss_development

test:
  <<: *default
  database: diyrss_test

production:
  <<: *default
  username: diyrss
  database: diyrss_production
