# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a09e3a3361a0e242706299deeca7024941b2a2fb1995acb9a1eaa4ed7d046934fcedc659bd67b55f3e3a4ea5dd4fbbb447d1909307338028ac343bdfe3f251a

test:
  secret_key_base: 87b0b098d7d034e4bab4e37ae68447d2c8ba01db28d9331af6fd4036b732431d58da30bfb0411aa7bf4dd09cacd782244b036033fc4412a970e5ae1ad8c6180a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: bb9762f1785ee28ea23ed04244531d3e215ed805fbab9f22e06528220a4a138abdc6db378f093ed3affbbd4ef79ff6284819c100035149159d7fecaa51297883
